### ISSUE TITLE
rgba colors not correctly parsed

### ISSUE THREAD

**Issue by razvantudorache** [raulmelo/addon-variablecss-theme#1]
Because of this `replace(/,/g,';')` (see: [actions.ts#L36](https://github.com/raulmelo/addon-variablecss-theme/blob/main/src/utils/actions.ts#L36)) the css variables that have `rgba` values (e.g. `rgba(0, 168, 255, 0.7)` ), are not correctly parsed. It's parsed: `rgba(0; 168; 255; 0.7)`

Comma should not be replaced with semi-colon for css variables value.

**Comment by raulmelo** [comment]
Hei, @lambry!
Thank you for your collaboration. I'm approving and add the new version with your commit.

**Comment by raulmelo** [comment]
@razvantudorache update new version, good suggestion.
